apiVersion: v1
kind: Namespace
metadata:
  name: pi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  namespace: pi
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: pi
spec:
  selector:
    app: nginx
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80