apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-pi-cert
  namespace: pi
spec:
  commonName: cows.com
  secretName: my-pi-cert01 # the secret where the issued cert stores in
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - cows.com